### PR TITLE
Support workflow job environments

### PR DESCRIPTION
**Pull request by deimantastumas**
## Summary
GitHub Actions environments are now generally available for GitHub Actions on GitHub Enterprise Server. Changes address it by adding the `Environment` field into the workflow job struct.

## Use Cases
Adding the environment to the workflow job when building a pipeline.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by deimantastumas** [comment]
Just wanted to point out that I've signed the CLA after submitting the PR.

**Comment by dmikusa-pivotal** [comment]
>Just wanted to point out that I've signed the CLA after submitting the PR.

Thanks for signing the CLA. The EasyCLA bot should pick up on that if things are complete, but there is still something it doesn't like. Can you try clicking the doc link in the note from EasyCLA and following the instructions there? It is particular about the way you submit stuff so that it can verify you've signed the CLA. We are not permitted to accept a PR unless EasyCLA gives the 👍 so we need to get that resolved.

Aside from that, the PR is small and looks reasonable. Can you expand on why it's needed though? I see you adding the field to the struct, but nothing is using it. What's missing by not having it in there? What doesn't work at present? I'm just trying to understand the purpose of adding it. Thanks

**Comment by deimantastumas** [comment]
Thank you for such a quick response! Looks like I've managed to settle down CLA issues :D

> Can you expand on why it's needed though?
I'm aware that `pipeline-builder` itself doesn't have any uses for environments as of this day, perhaps it will be useful in the future, since GitHub supports it. As for my needs - I'm using `pipeline-builder` as a Go library in my separate application that converts DroneCI pipelines into GHA workflows. Most of my workflows require the usage of environments, hence it would be great if the builder supported this field 👍

**Comment by dmikusa-pivotal** [comment]
OK, thanks for the additional detail. That seems reasonable. I will need to review and see how this will impact our pipelines. I'll get back to you shortly.

**Review by dmikusa-pivotal — APPROVED** [review]

**Pull request merged**
