### PR TITLE
Control build.sh and .gitignore

### LINKED ISSUE #1100: Enable pipeline builder to manage scripts/build.sh
## Describe the Enhancement

Right now the scripts/build.sh file is managed by each individual repo, but it could be templated and owned by pipeline builder.

## Possible Solution

1. Add a config section to pipeline descriptor to control how the build.sh script is generated.

2. Modify octo to generate that file, taking into consideration the descriptor section.

The generated script should match exactly the existing scripts.

## Motivation

It is painful to make changes to the build.sh script because you have to change every repo individually. This will centralize the script contents so it can be updated more easily.

### PR DESCRIPTION
**Pull request by dmikusa**
## Summary

This PR adds control of the build.sh and .gitignore files over to `octo`. When it runs, it will generate those files. The build.sh script comes from a template file which is static at the moment. This could be modified to be a go template or something more flexible if necessary in the future. The .gitignore file is generated from a list of strings. For now, this ends up being static, but we could add in logic to generate the list dynamically if needed in the future.

## Use Cases

Automatically update the build.sh and .gitignore files, which are basically the same across all the repos. This helps make changes to the resources easier to apply.

Resolves #1100 

The only caveat to this change is that we'll need to be very careful on the first run though. This change assumes that the build.sh file is the same for all managed buildpacks. I think that's true, but the first time we'll want to merge all the PRs manually and review carefully to make sure that we're not overwriting anything important.

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by anthonydahanne** [comment]
Thanks @dmikusa for providing a way to automate those changes.

Does `octo/build-script.sh` support the `helper`s binaries?

For example, I've already encountered 4 projects that not only have main/detect/build BUT also have `helper`:

* https://github.com/paketo-buildpacks/ca-certificates/pull/218/files#diff-5f54cb49d0e28117084fad482c0daf89502d4ecb329230071fcf78e56dc939b3R39
* https://github.com/paketo-buildpacks/bellsoft-liberica/pull/563/files#diff-3d64996115d0ac3b74e36f57ce6b00d6b4982614c41b1ed39eab8ef43b2e9a2bR5
* https://github.com/paketo-buildpacks/datadog/pull/290/files#diff-3d64996115d0ac3b74e36f57ce6b00d6b4982614c41b1ed39eab8ef43b2e9a2bR11
* https://github.com/paketo-buildpacks/spring-boot/pull/450/files#diff-3d64996115d0ac3b74e36f57ce6b00d6b4982614c41b1ed39eab8ef43b2e9a2bR6

**Comment by dmikusa** [comment]
Thanks, I hit some similar issues. I have a change to account for this but am doing some more testing with it. Will update soon.

**Comment by dmikusa** [comment]
Ok, I think this is ready now.

What I added is a `helpers:` section in the pipeline-descriptor.yml file. That is an optional map that is used to define any additional binaries that should be compiled for this buildpack. The format is key=path and value=go-mod-build-path. The path is relative to the os/arch-specific folder in the generated buildpack file structure. The go-mod-build-path is the part you'd pass to `go build` to tell it what to build.

Ex: build cmd/helper from the current buildpack

```
helpers:
  "bin/helper": "$GOMOD/cmd/helper"
```

Ex: build cmd/helper from libjvm

```
helpers:
  "bin/helper": "github.com/paketo-buildpacks/libjvm/cmd/helper"
```

Then you end up with a structure like:

```
linux/amd64/bin:
total 21392
lrwxr-xr-x  1 dmikusa  staff        4 Mar 16 17:29 build@ -> main
lrwxr-xr-x  1 dmikusa  staff        4 Mar 16 17:29 detect@ -> main
-rwxr-xr-x  1 dmikusa  staff  4325528 Mar 16 17:29 helper*
-rwxr-xr-x  1 dmikusa  staff  6619288 Mar 16 17:29 main*

linux/arm64/bin:
total 21392
lrwxr-xr-x  1 dmikusa  staff        4 Mar 16 17:29 build@ -> main
lrwxr-xr-x  1 dmikusa  staff        4 Mar 16 17:29 detect@ -> main
-rwxr-xr-x  1 dmikusa  staff  4325528 Mar 16 17:29 helper*
-rwxr-xr-x  1 dmikusa  staff  6619288 Mar 16 17:29 main*
```

**Comment by dmikusa** [comment]
When we release this, we need to be careful. We can't auto-merge all the PRs because some of the buildpacks will need updates to pipeline-descriptor.yml (for helpers to be added).

**Review by anthonydahanne — APPROVED** [review]
all good!

**Pull request merged**
